# Generated by Django 4.2.2 on 2023-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone_number',
            field=models.PositiveSmallIntegerField(max_length=11),
        ),
    ]
