# Generated by Django 4.2.2 on 2023-07-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
